version: '3.6'
services:
  frontend:
    build:
      context: ./angular-ui/app
      dockerfile: Dockerfile
    volumes:
      - .:/web
    ports:
      - "4200:4200"
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 32782:1972
      - 32783:52773
      - 32784:53773
    volumes:
      - durable:/durable
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
volumes:
  durable: 